"""empty message

Revision ID: 299cdb83ef82
Revises: 3e4c968a46ca
Create Date: 2020-09-11 18:53:43.068054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '299cdb83ef82'
down_revision = '3e4c968a46ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kotokan_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kotokan_id'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('kotokan_id', table_name='game_status')
    op.drop_table('game_status')
    op.add_column('enrollment', sa.Column('game_status', sa.Text(), nullable=False))
    op.add_column('student', sa.Column('avatar', sa.String(length=255), nullable=False))
    op.add_column('student', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'student', ['avatar'])
    op.create_foreign_key(None, 'student', 'school', ['school_id'], ['id'])
    op.add_column('user', sa.Column('school_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'school_id')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'school_id')
    op.drop_column('student', 'avatar')
    op.drop_column('enrollment', 'game_status')
    op.create_table('game_status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kotokan_id', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('enrollment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], name='game_status_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('kotokan_id', 'game_status', ['kotokan_id'], unique=True)
    op.drop_table('school')
    # ### end Alembic commands ###
