"""empty message

Revision ID: 8a569279eccb
Revises: 299cdb83ef82
Create Date: 2020-09-18 19:21:39.532426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a569279eccb'
down_revision = '299cdb83ef82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment', 'game_status')
    op.add_column('student', sa.Column('game_status', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'game_status')
    op.add_column('enrollment', sa.Column('game_status', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
